/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as CallForPapersIndexRouteImport } from './routes/call-for-papers/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as DatesIndexRouteImport } from './routes/dates/index'
import { Route as VenueIndexRouteImport } from './routes/venue/index'
import { Route as WorkshopsIndexRouteImport } from './routes/workshops/index'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallForPapersIndexRoute = CallForPapersIndexRouteImport.update({
  id: '/call-for-papers/',
  path: '/call-for-papers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesIndexRoute = DatesIndexRouteImport.update({
  id: '/dates/',
  path: '/dates/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueIndexRoute = VenueIndexRouteImport.update({
  id: '/venue/',
  path: '/venue/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsIndexRoute = WorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/call-for-papers/': typeof CallForPapersIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/dates/': typeof DatesIndexRoute
  '/venue/': typeof VenueIndexRoute
  '/workshops/': typeof WorkshopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/call-for-papers': typeof CallForPapersIndexRoute
  '/contact': typeof ContactIndexRoute
  '/dates': typeof DatesIndexRoute
  '/venue': typeof VenueIndexRoute
  '/workshops': typeof WorkshopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/call-for-papers/': typeof CallForPapersIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/dates/': typeof DatesIndexRoute
  '/venue/': typeof VenueIndexRoute
  '/workshops/': typeof WorkshopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call-for-papers/'
    | '/contact/'
    | '/dates/'
    | '/venue/'
    | '/workshops/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/call-for-papers' | '/contact' | '/dates' | '/venue' | '/workshops'
  id:
    | '__root__'
    | '/(home)/'
    | '/call-for-papers/'
    | '/contact/'
    | '/dates/'
    | '/venue/'
    | '/workshops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  CallForPapersIndexRoute: typeof CallForPapersIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  DatesIndexRoute: typeof DatesIndexRoute
  VenueIndexRoute: typeof VenueIndexRoute
  WorkshopsIndexRoute: typeof WorkshopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-for-papers/': {
      id: '/call-for-papers/'
      path: '/call-for-papers'
      fullPath: '/call-for-papers/'
      preLoaderRoute: typeof CallForPapersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates/': {
      id: '/dates/'
      path: '/dates'
      fullPath: '/dates/'
      preLoaderRoute: typeof DatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/': {
      id: '/venue/'
      path: '/venue'
      fullPath: '/venue/'
      preLoaderRoute: typeof VenueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/': {
      id: '/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof WorkshopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  CallForPapersIndexRoute: CallForPapersIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  DatesIndexRoute: DatesIndexRoute,
  VenueIndexRoute: VenueIndexRoute,
  WorkshopsIndexRoute: WorkshopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
