/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as SubmissionsIndexRouteImport } from './routes/submissions/index'
import { Route as WorkshopsIndexRouteImport } from './routes/workshops/index'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsIndexRoute = WorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/workshops/': typeof WorkshopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
  '/workshops': typeof WorkshopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/workshops/': typeof WorkshopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/submissions/' | '/workshops/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/submissions' | '/workshops'
  id: '__root__' | '/(home)/' | '/submissions/' | '/workshops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
  WorkshopsIndexRoute: typeof WorkshopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/': {
      id: '/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/': {
      id: '/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof WorkshopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
  WorkshopsIndexRoute: WorkshopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
